from __future__ import annotations

from typing import Any

import pandas as pd


def normalize_student_id(
    student_id: str,
    dataset: pd.DataFrame,
    student_id_column: str,
) -> Any:
    """
    Convert a student ID from the user's query into the same
    general data type used by the dataset's ID column.
    """

    id_series = dataset[student_id_column]

    if pd.api.types.is_integer_dtype(id_series):
        return int(student_id)

    if pd.api.types.is_float_dtype(id_series):
        return float(student_id)

    return str(student_id)


def find_student_records(
    dataset: pd.DataFrame,
    student_id_column: str,
    student_id: str,
) -> pd.DataFrame:
    """
    Return every record associated with a student ID.
    """

    normalized_id = normalize_student_id(
        student_id=student_id,
        dataset=dataset,
        student_id_column=student_id_column,
    )

    return dataset[
        dataset[student_id_column] == normalized_id
    ].copy()


def format_value(value: Any) -> str:
    """
    Format a dataset value for display.
    """

    if pd.isna(value):
        return "Missing"

    if isinstance(value, float):
        if value.is_integer():
            return str(int(value))

        return f"{value:.4f}"

    return str(value)


def format_student_record(
    student_records: pd.DataFrame,
    student_id: str,
    student_id_column: str,
    target_column: str | None = None,
) -> str:
    """
    Convert a student's records into a Markdown response.
    """

    if student_records.empty:
        return (
            f"I could not find student **{student_id}** "
            "in the currently loaded dataset."
        )

    response_lines = [
        f"## Student {student_id}",
        "",
        (
            f"SEAID found **{len(student_records):,} "
            f"record(s)** for this student."
        ),
        "",
    ]

    # For the current test dataset, this will usually be one row.
    # For temporal datasets, the same student may have several rows.
    for record_number, (_, row) in enumerate(
        student_records.iterrows(),
        start=1,
    ):
        if len(student_records) > 1:
            response_lines.extend(
                [
                    f"### Record {record_number}",
                    "",
                ]
            )

        for column_name, value in row.items():
            if column_name == student_id_column:
                continue

            formatted_name = (
                column_name
                .replace("_", " ")
                .strip()
                .title()
            )

            formatted_value = format_value(value)

            response_lines.append(
                f"- **{formatted_name}:** {formatted_value}"
            )

        response_lines.append("")

    if (
        target_column is not None
        and target_column in student_records.columns
    ):
        target_values = (
            student_records[target_column]
            .dropna()
            .unique()
            .tolist()
        )

        if target_values:
            latest_target = target_values[-1]

            response_lines.extend(
                [
                    "### Recorded Outcome",
                    "",
                    (
                        f"The value in **`{target_column}`** is "
                        f"**{format_value(latest_target)}**."
                    ),
                    "",
                    (
                        "This is the recorded dataset outcome, "
                        "not yet a prediction generated by a "
                        "trained SEAID model."
                    ),
                ]
            )

    return "\n".join(response_lines)